name: Build and Analyze Invoice Generator

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Pour SonarCloud

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Maven (pour SonarCloud)
        run: mvn -B clean verify sonar:sonar -Dsonar.projectKey=danyfrock_invoice-generator -Dsonar.organization=danyfrock -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }}

  build-and-release:
    runs-on: windows-latest
    needs: sonarcloud  # Attend que SonarCloud finisse
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Download JavaFX SDK
        run: |
          curl -L -o javafx-sdk.zip https://download2.gluonhq.com/openjfx/23.0.2/openjfx-23.0.2_windows-x64_bin-sdk.zip
          unzip javafx-sdk.zip -d C:\JavaFX
        shell: cmd

      - name: Build with Maven
        run: mvn -B clean package
        shell: cmd

      - name: Extract version from pom.xml
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_version
        run: |
          for /f "tokens=2 delims=<version></version>" %%i in ('findstr /r "<version>[0-9]*\.[0-9]*\.[0-9]*-SNAPSHOT</version>" pom.xml') do (
            set "VERSION=%%i"
            set "EXE_VERSION=%%i"
          )
          set "EXE_VERSION=%EXE_VERSION:-SNAPSHOT=%"
          set "JAR_NAME=InvoiceGenerator-%VERSION%.jar"
          set "EXE_NAME=InvoiceGenerator-%EXE_VERSION%.exe"
          echo VERSION=%VERSION% >> %GITHUB_ENV%
          echo EXE_VERSION=%EXE_VERSION% >> %GITHUB_ENV%
          echo JAR_NAME=%JAR_NAME% >> %GITHUB_ENV%
          echo EXE_NAME=%EXE_NAME% >> %GITHUB_ENV%
        shell: cmd

      - name: Create runtime with jlink
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          jlink --module-path "C:\Program Files\Eclipse Adoptium\jdk-22.0.2+9\jmods;C:\JavaFX\javafx-sdk-23.0.2\lib" --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.base,java.logging --output target\runtime
        shell: cmd

      - name: Generate executable with jpackage
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          jpackage --input target --main-jar ${{ env.JAR_NAME }} --main-class com.invoicegenerator.Main --name InvoiceGenerator --app-version ${{ env.EXE_VERSION }} --type exe --runtime-image target\runtime --win-dir-chooser --dest target --verbose
        shell: cmd

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.EXE_VERSION }}
          name: Release v${{ env.EXE_VERSION }}
          files: target/${{ env.EXE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}