name: Build and Release

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Pour générer un .exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version from tag
        run: |
          echo VERSION=%GITHUB_REF_NAME% >> %GITHUB_ENV%
          echo EXE_VERSION=%GITHUB_REF_NAME:v=% >> %GITHUB_ENV%
        shell: cmd

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Download JavaFX SDK
        run: |
          curl -L -o javafx-sdk.zip https://download2.gluonhq.com/openjfx/23.0.2/openjfx-23.0.2_windows-x64_bin-sdk.zip
          unzip javafx-sdk.zip -d javafx-sdk
        shell: cmd

      - name: Build with Maven
        run: mvn -B clean package

      - name: Create runtime image with jlink
        run: |
          jlink --module-path "%JAVA_HOME%\jmods;javafx-sdk\javafx-sdk-23.0.2\lib" \
                --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.base,java.logging \
                --output target/runtime

      - name: Package executable with jpackage
        run: |
          jpackage --input target \
                   --main-jar target/invoice-generator-${{ env.VERSION }}.jar \
                   --main-class com.invoicegenerator.Main \
                   --name InvoiceGenerator \
                   --app-version ${{ env.EXE_VERSION }} \
                   --type exe \
                   --runtime-image target/runtime \
                   --win-dir-chooser \
                   --dest target \
                   --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: InvoiceGenerator-${{ env.EXE_VERSION }}
          path: target/InvoiceGenerator-${{ env.EXE_VERSION }}.exe