name: Build and Release Invoice Generator

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # On utilise Windows pour générer un .exe

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer JDK 22
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'  # Eclipse Temurin est une distrib fiable

      # Étape 3 : Télécharger et configurer JavaFX SDK
      - name: Download JavaFX SDK
        run: |
          curl -L -o javafx-sdk.zip https://download2.gluonhq.com/openjfx/23.0.2/openjfx-23.0.2_windows-x64_bin-sdk.zip
          unzip javafx-sdk.zip -d C:\JavaFX
        shell: cmd

      # Étape 4 : Nettoyer et construire avec Maven
      - name: Build with Maven
        run: |
          mvn -B clean package
          mvn -B javadoc:javadoc
        shell: cmd

      # Étape 5 : Extraire la version du pom.xml
      - name: Extract version from pom.xml
        id: get_version
        run: |
          for /f "tokens=2 delims=<version></version>" %%i in ('findstr /r "<version>[0-9]*\.[0-9]*\.[0-9]*-SNAPSHOT</version>" pom.xml') do (
            set "VERSION=%%i"
            set "EXE_VERSION=%%i"
          )
          set "VERSION=%VERSION: =%"
          set "EXE_VERSION=%EXE_VERSION:-SNAPSHOT=%"
          echo VERSION=%VERSION% >> %GITHUB_ENV%
          echo EXE_VERSION=%EXE_VERSION% >> %GITHUB_ENV%
          echo Version extracted: VERSION=%VERSION%, EXE_VERSION=%EXE_VERSION%
        shell: cmd

      # Étape 6 : Créer le runtime avec jlink
      - name: Create runtime with jlink
        run: |
          jlink --module-path "C:\Program Files\Eclipse Adoptium\jdk-22.0.2+9\jmods;C:\JavaFX\javafx-sdk-23.0.2\lib" --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.base,java.logging --output target\runtime
        shell: cmd

      # Étape 7 : Générer l'exécutable avec jpackage
      - name: Generate executable with jpackage
        run: |
          jpackage --input target --main-jar "InvoiceGenerator-${{ env.VERSION }}.jar" --main-class com.invoicegenerator.Main --name InvoiceGenerator --app-version ${{ env.EXE_VERSION }} --type exe --runtime-image target\runtime --win-dir-chooser --dest target --verbose
        shell: cmd

      # Étape 8 : Publier dans une release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: v${{ env.EXE_VERSION }}
          name: Release v${{ env.EXE_VERSION }}
          files: target/InvoiceGenerator-${{ env.EXE_VERSION }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
