name: Build and Analyze Invoice Generator

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Download JavaFX SDK
        run: |
          curl -L -o javafx-sdk.zip https://download2.gluonhq.com/openjfx/23.0.2/openjfx-23.0.2_windows-x64_bin-sdk.zip
          unzip javafx-sdk.zip -d javafx-sdk
        shell: cmd

      - name: Extract version from pom.xml
        id: get_version
        run: |
          for /f "tokens=2 delims=<version></version>" %%i in ('findstr /r "<version>[0-9]*\.[0-9]*\.[0-9]*-SNAPSHOT</version>" pom.xml') do (
            set "VERSION=%%i"
            set "EXE_VERSION=%%i"
          )
          set "EXE_VERSION=%EXE_VERSION:-SNAPSHOT=%"
          set "JAR_NAME=InvoiceGenerator-%VERSION%.jar"
          set "EXE_NAME=InvoiceGenerator-%EXE_VERSION%.exe"
          echo VERSION=%VERSION% >> $GITHUB_ENV
          echo EXE_VERSION=%EXE_VERSION% >> $GITHUB_ENV
          echo JAR_NAME=%JAR_NAME% >> $GITHUB_ENV
          echo EXE_NAME=%EXE_NAME% >> $GITHUB_ENV
          echo Version extracted: VERSION=%VERSION%, EXE_VERSION=%EXE_VERSION%, JAR_NAME=%JAR_NAME%, EXE_NAME=%EXE_NAME%
        shell: cmd

      - name: Build with Maven
        run: mvn -B clean package
        shell: cmd

      - name: Install with Maven
        run: mvn install -U
        shell: cmd

      - name: Create runtime with jlink
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          jlink --module-path "%JAVA_HOME%\jmods;javafx-sdk\javafx-sdk-23.0.2\lib" --add-modules javafx.controls,javafx.fxml,javafx.graphics,javafx.base,java.logging --output target\runtime --verbose
          dir target\runtime
        shell: cmd

      - name: Copy dependencies
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          dir target\libs
          mvn dependency:copy-dependencies -DoutputDirectory="target\libs"
        shell: cmd

      - name: Debug target directory
        if: startsWith(github.ref, 'refs/tags/v')
        run: dir target
             dir target\libs
             dir javafx-sdk
             dir javafx-sdk\javafx-sdk-23.0.2
             dir javafx-sdk\javafx-sdk-23.0.2\lib
        shell: cmd

      - name: Generate executable with jpackage
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          jpackage --input target --module InvoiceGenerator/com.invoicegenerator.Main --module-path "target\libs" --name InvoiceGenerator --app-version "${{ env.EXE_VERSION }}" --type "exe" --runtime-image target\runtime --win-dir-chooser --dest target --verbose
          dir target
        shell: cmd

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.EXE_VERSION }}
          name: Release v${{ env.EXE_VERSION }}
          files: target/${{ env.EXE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}